#!/usr/bin/env bash

# i am a lazy fuck! this deploys the code locally from my desktop/laptop to carbuncle, and builds it via siren, a pi 5 (both ARM)

set -euo pipefail
exec nixos-rebuild switch \
  --flake .#carbuncle \
  --build-host root@siren \
  --target-host root@carbuncle \
  "$@"
